spring.application.name=addio_celibrato

spring.datasource.url=jdbc:postgresql://localhost:5432/addio_celibato?currentSchema=app_schema,public
spring.datasource.username=addio_celibato_app
spring.datasource.password=V4Q4y5cOpt7S
spring.jpa.properties.hibernate.default_schema=app_schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog.yaml
spring.liquibase.liquibase-schema=public
spring.liquibase.password=password
spring.liquibase.default-schema=app_schema

spring.data.web.pageable.serialization-mode=via-dto

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

app.cors.allowed-origins=http://localhost:55255, https://www.tuosito.it

springdoc.openapi.servers[0].url=${SERVER_URL:http://localhost:8080}

telegram.bot.token=8619336688:AAE_NtaRgcMJbmieUhcJqspxdLQA_4zSsVc
telegram.chat.id=-5180847974